sudo: required
dist: trusty
addons:
    postgresql: "9.5"
services:
    - postgresql
language: node_js
node_js:
  - "10"
  - "8"  
  - "6"
before_script:
  - psql -c 'create database pgboss' -U postgres
script:
  - npm run forcover
cache: yarn
